### PR TITLE
Update pyrad to tip 4/2021

### PR DESCRIPTION
**Pull request by anushadatar**
Not sure if a pull request is the best format for the because of the amount of changes associated with this (but there shouldn't be any merge conflicts), but this PR is for upgrading our fork of pyrad to tip. 

We currently use version [2.4](https://pypi.org/project/pyrad/2.4/), which is the official pypi version of pyrad. This would pull our working version to tip, which would be useful for developing features associated with RADIUS packet fragmentation and trying to upstream them. For what it's worth, there aren't too many dramatic changes between this version and tip.

I tested this version by installing as my local version of pyrad and then running the tests in meter_radius to confirm that they worked as expected; happy to do more rigorous testing but would appreciate some additional guidance on what those tests should look like.

### CODE REVIEW

**Comment by pallas** [comment]
Looking

**Comment by anushadatar** [comment]
> Looking

Thanks! The "assign" on that was definitely accidental, and I still really appreciate the quick turnaround on this!

**Comment by pallas** [comment]
Seems reasonable. I'd do a rebase+merge rather than a merge commit since this really should just be tracking mainline. If you want to update the version in package cloud, lmk and I'll walk you through it.

**Review by pallas — APPROVED** [review]

**Comment by anushadatar** [comment]
Will go ahead and rebase merge this and then get in touch with you wrt the package cloud update. Thanks!

**Pull request merged**
